---
title: "Untitled"
author: "Zachary Safir"
date: "2/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F)
```


```{r}

df <- data.frame(X1 = c("Alaska",NA, NA,"AM West",NA),
                 X2 = c("on time","delayed",NA,"on time","delayed"),
                 `Los Angeles` = c(497,62,NA,694,117),
                 Phoenix = as.numeric( gsub(",","",c(221,12,NA,'4,840',415))),
                 `San Diego` = c(212,20,NA,383,65),
                 `San Francisco` = c(503,102,NA,320,129),
                 Seattle =  as.numeric( gsub(",","",c('1,841',305,NA,201,61)))
                 )
```
 

```{r}
write.csv(df,"flight.csv",row.names=FALSE)


```



```{r}
flights <- read.csv("https://raw.githubusercontent.com/zachsfr/RTest/main/flight.csv")
```


```{r}



t <- flights %>%
filter(X2=='on time') %>%
  select(X1)


flights %>% 
  select(-X1) %>%
  filter(X2 == "delayed") %>%
cbind(t) %>%
  relocate(X1) %>%
  rbind(flights) %>%
  filter(!is.na(X1)) %>%
  pivot_longer(Los.Angeles:Seattle)


bind_cols()
```


```{r}


flights <- flights %>%
  pivot_longer(Los.Angeles:Seattle,
               names_to = "City",
               values_to  = "Count",
               values_drop_na=T)  %>%
  fill(X1) %>%
  pivot_wider(names_from =X2,values_from =Count) %>%

  rename(Airline = X1, On.Time = `on time`,Delayed = delayed) %>%
  mutate(delay_prop=  round(((Delayed/(Delayed + On.Time))),  3 ) ,
         on_time_prop =  round(((On.Time/(Delayed + On.Time))),  3 )
         
         ) 


  
```



```{r}


 flights %>%
  ggplot(aes(x=reorder(City,delay_prop),y=delay_prop,fill=Airline)) + 
  geom_bar(stat = 'identity',position=position_dodge())   +
  geom_text(aes(label=delay_prop), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5) +

  labs(y = ("Departure Delay"),x = ("City"),
      title = ("Proportion of Depatures with Delays per City and Airline")  ) +
  scale_x_discrete(labels = c("Phoenix","San Diego","Los Angeles","Seattle","San Francisco"))+
  scale_fill_brewer(palette="Paired") +
  theme_minimal()

```

  
  
```{r}

flights %>%
  
  group_by(Airline) %>%
  summarise (m = round((sum(Delayed)/ sum(Delayed+On.Time)),3 ) )   %>%
  ggplot(aes(x=Airline, y=m ,fill=Airline)) + 
  geom_bar(stat = 'identity') +
  geom_text(aes(label=m ), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
 

```
  
  
  
 
```{r}


flights %>%
group_by(Airline) %>%
  filter(City != "Phoenix") %>%
  summarise (m = round((sum(Delayed)/ sum(Delayed+On.Time)),3 ) )   %>%
  ggplot(aes(x=Airline, y=m ,fill=Airline)) + 
  geom_bar(stat = 'identity') +
  geom_text(aes(label=m ), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
 

```
  












